name: JS test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '42 7 * * *'

defaults:
  run:
    shell: bash

jobs:
  jstest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Install k6
        run: go install go.k6.io/k6@master
      - name: Run JS tests
        run: make test-js
